# Generated by Django 3.1.5 on 2021-08-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date2', models.DateField(null=True)),
                ('open1', models.FloatField(null=True)),
                ('high', models.FloatField(null=True)),
                ('low', models.FloatField(null=True)),
                ('close', models.FloatField(null=True)),
                ('wap', models.FloatField(null=True)),
                ('no_of_shares', models.IntegerField()),
                ('no_of_trades', models.IntegerField()),
                ('total_turnover', models.FloatField(null=True)),
                ('deliverable', models.IntegerField()),
                ('per_of_del_qty_to_trd_qty', models.FloatField(null=True)),
                ('spread_h_l', models.FloatField(null=True)),
                ('spread_c_o', models.FloatField(null=True)),
            ],
        ),
    ]
