# Generated by Django 3.1.5 on 2021-08-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20210822_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date2',
            new_name='date1',
        ),
    ]
