# Generated by Django 3.1.5 on 2021-08-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20210823_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='close',
            new_name='Close',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='date1',
            new_name='Date1',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='deliverable',
            new_name='Deliverable',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='high',
            new_name='High',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='low',
            new_name='Low',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='no_of_shares',
            new_name='No_Of_Shares',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='no_of_trades',
            new_name='No_Of_Trades',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='open1',
            new_name='Open',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='per_of_del_qty_to_trd_qty',
            new_name='Per_Of_Del_Qty_To_Trd_Qty',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='spread_c_o',
            new_name='Spread_C_O',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='spread_h_l',
            new_name='Spread_H_L',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='total_turnover',
            new_name='Total_Turnover',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='wap',
            new_name='WAP',
        ),
    ]
